### ISSUE TITLE
Cannot find module './build/Release/pcap_binding'

### ISSUE THREAD

**Issue by illnino** [pownjs/pown-now#1]
## ENV

```bash
➜  playground npm -v
3.10.10
➜  playground node -v
v6.10.2
```

```
➜  playground npm list
/Users/its/Project/nino/playground
├─┬ pown-now@0.1.0
│ ├─┬ chalk@1.1.3
│ │ ├── ansi-styles@2.2.1
│ │ ├── escape-string-regexp@1.0.5
│ │ ├─┬ has-ansi@2.0.0
│ │ │ └── ansi-regex@2.1.1
│ │ ├─┬ strip-ansi@3.0.1
│ │ │ └── ansi-regex@2.1.1
│ │ └── supports-color@2.0.0
│ ├─┬ opn@4.0.2
│ │ ├── object-assign@4.1.1
│ │ └─┬ pinkie-promise@2.0.1
│ │   └── pinkie@2.0.4
│ ├─┬ ws@2.3.1
│ │ ├── safe-buffer@5.0.1
│ │ └── ultron@1.1.0
│ └─┬ ws-pcap2@3.3.1
│   ├── nan@2.6.2
│   └── socketwatcher@0.3.0
└─┬ pown-tips@0.0.3
  ├─┬ chalk@1.1.3
  │ ├── ansi-styles@2.2.1
  │ ├── escape-string-regexp@1.0.5
  │ ├─┬ has-ansi@2.0.0
  │ │ └── ansi-regex@2.1.1
  │ ├── strip-ansi@3.0.1
  │ └── supports-color@2.0.0
  ├─┬ inquirer@3.0.6
  │ ├── ansi-escapes@1.4.0
  │ ├─┬ cli-cursor@2.1.0
  │ │ └─┬ restore-cursor@2.0.0
  │ │   ├─┬ onetime@2.0.1
  │ │   │ └── mimic-fn@1.1.0
  │ │   └── signal-exit@3.0.2
  │ ├── cli-width@2.1.0
  │ ├─┬ external-editor@2.0.1
  │ │ └─┬ tmp@0.0.31
  │ │   └── os-tmpdir@1.0.2
  │ ├── figures@2.0.0
  │ ├── lodash@4.17.4
  │ ├── mute-stream@0.0.7
  │ ├─┬ run-async@2.3.0
  │ │ └── is-promise@2.1.0
  │ ├── rx@4.1.0
  │ ├─┬ string-width@2.0.0
  │ │ └── is-fullwidth-code-point@2.0.0
  │ └── through@2.3.8
  ├── marked@0.3.6
  ├─┬ marked-terminal@2.0.0
  │ ├─┬ cardinal@1.0.0
  │ │ ├── ansicolors@0.2.1
  │ │ └─┬ redeyed@1.0.1
  │ │   └── esprima@3.0.0
  │ ├─┬ cli-table@0.3.1
  │ │ └── colors@1.0.3
  │ ├── lodash.assign@4.2.0
  │ └─┬ node-emoji@1.5.1
  │   └── string.prototype.codepointat@0.2.0
  └── wordwrap@1.0.0
```

## Error Log

```bash
➜  playground pown now eth0

 _______ _______ _  _  _
(_______|_______|_)(_)(_)
 _     _ _     _ _  _  _
| |   | | |   | | || || |
| |   | | |___| | || || |
|_|   |_|_____/ _____/


/Users/its/.nvm/versions/node/v6.10.2/lib/node_modules/pown/node_modules/yargs/yargs.js:1078
      else throw err
           ^

Error: Cannot find module './build/Release/pcap_binding'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/its/.nvm/versions/node/v6.10.2/lib/node_modules/pown/node_modules/ws-pcap2/index.js:6:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

## Reproduction Steps

```bash
npm install -g pown
npm install pown-now --save
pown now eth0
```

## Cause?

[ws-pcap2](https://www.npmjs.com/package/ws-pcap2)

>To use this library in your own program, index.js and pcap_binding.node must be in NODE_PATH. npm takes care of this automatically.

**Comment by pdparchitect** [comment]
What I think it is happening is that you are missing libpcap plus the headers in order to compile the ws-pcap2 binding. You can install these in debian like this:

```sh
$ apt-get install libpcap-dev
```

After that all you need to

```sh
$ npm install -g pown
```

If the command was successful you will be able to use pown now as normal like this:

```sh
$ pown now eth0
```

Can you let me know if this worked?

**Comment by illnino** [comment]
Unfortunately, I am using Mac.

I tried 

```
➜  playground brew install libpcap
➜  playground npm install -g pown

```

Then

```bash
➜  playground pown now eth0

 _______ _______ _  _  _
(_______|_______|_)(_)(_)
 _     _ _     _ _  _  _
| |   | | |   | | || || |
| |   | | |___| | || || |
|_|   |_|_____/ _____/


/Users/its/.nvm/versions/node/v6.10.2/lib/node_modules/pown/node_modules/yargs/yargs.js:1078
      else throw err
           ^

Error: Cannot find module './build/Release/pcap_binding'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/its/.nvm/versions/node/v6.10.2/lib/node_modules/pown/node_modules/ws-pcap2/index.js:6:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

Same Error.

**Comment by illnino** [comment]
## OS

Mac OS 10.11.6

**Comment by pdparchitect** [comment]
Can you send us the log of `npm install -g pown`?

**Comment by illnino** [comment]
```log
/Users/its/.nvm/versions/node/v6.10.2/bin/pown -> /Users/its/.nvm/versions/node/v6.10.2/lib/node_modules/pown/index.js

> socketwatcher@0.3.0 install /Users/its/.nvm/versions/node/v6.10.2/lib/node_modules/pown/node_modules/socketwatcher
> node-gyp rebuild

  c++ '-DNODE_GYP_MODULE_NAME=socketwatcher' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/Users/its/.node-gyp/6.10.2/include/node -I/Users/its/.node-gyp/6.10.2/src -I/Users/its/.node-gyp/6.10.2/deps/uv/include -I/Users/its/.node-gyp/6.10.2/deps/v8/include -I../../nan  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++0x -fno-rtti -fno-exceptions -fno-threadsafe-statics -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/socketwatcher/socket_watcher.o.d.raw   -c -o Release/obj.target/socketwatcher/socket_watcher.o ../socket_watcher.cpp
  c++ -bundle -undefined dynamic_lookup -Wl,-no_pie -Wl,-search_paths_first -mmacosx-version-min=10.7 -arch x86_64 -L./Release  -o Release/socketwatcher.node Release/obj.target/socketwatcher/socket_watcher.o 

> ws-pcap2@3.3.1 install /Users/its/.nvm/versions/node/v6.10.2/lib/node_modules/pown/node_modules/ws-pcap2
> node-gyp rebuild

  c++ '-DNODE_GYP_MODULE_NAME=pcap_binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/Users/its/.node-gyp/6.10.2/include/node -I/Users/its/.node-gyp/6.10.2/src -I/Users/its/.node-gyp/6.10.2/deps/uv/include -I/Users/its/.node-gyp/6.10.2/deps/v8/include -I../../nan  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++0x -fno-rtti -fno-exceptions -fno-threadsafe-statics -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/pcap_binding/src/pcap_binding.o.d.raw   -c -o Release/obj.target/pcap_binding/src/pcap_binding.o ../src/pcap_binding.cc
  c++ '-DNODE_GYP_MODULE_NAME=pcap_binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/Users/its/.node-gyp/6.10.2/include/node -I/Users/its/.node-gyp/6.10.2/src -I/Users/its/.node-gyp/6.10.2/deps/uv/include -I/Users/its/.node-gyp/6.10.2/deps/v8/include -I../../nan  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++0x -fno-rtti -fno-exceptions -fno-threadsafe-statics -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/pcap_binding/src/pcap_session.o.d.raw   -c -o Release/obj.target/pcap_binding/src/pcap_session.o ../src/pcap_session.cc
  c++ -bundle -undefined dynamic_lookup -Wl,-no_pie -Wl,-search_paths_first -mmacosx-version-min=10.7 -arch x86_64 -L./Release  -o Release/pcap_binding.node Release/obj.target/pcap_binding/src/pcap_binding.o Release/obj.target/pcap_binding/src/pcap_session.o -lpcap
/Users/its/.nvm/versions/node/v6.10.2/lib
└─┬ pown@1.5.0 
  ├─┬ pown-cli@0.3.0 
  │ ├─┬ pown-modules@0.4.3 
  │ │ ├─┬ async@2.3.0 
  │ │ │ └── lodash@4.17.4 
  │ │ └─┬ read-package-tree@5.1.5 
  │ │   ├── debuglog@1.0.1 
  │ │   ├─┬ dezalgo@1.0.3 
  │ │   │ ├── asap@2.0.5 
  │ │   │ └── wrappy@1.0.2 
  │ │   ├── once@1.4.0 
  │ │   ├─┬ read-package-json@2.0.5 
  │ │   │ ├─┬ glob@7.1.1 
  │ │   │ │ ├── fs.realpath@1.0.0 
  │ │   │ │ ├── inflight@1.0.6 
  │ │   │ │ ├── inherits@2.0.3 
  │ │   │ │ ├─┬ minimatch@3.0.3 
  │ │   │ │ │ └─┬ brace-expansion@1.1.7 
  │ │   │ │ │   ├── balanced-match@0.4.2 
  │ │   │ │ │   └── concat-map@0.0.1 
  │ │   │ │ └── path-is-absolute@1.0.1 
  │ │   │ ├── graceful-fs@4.1.11 
  │ │   │ ├─┬ json-parse-helpfulerror@1.0.3 
  │ │   │ │ └── jju@1.3.0 
  │ │   │ └─┬ normalize-package-data@2.3.8 
  │ │   │   ├── hosted-git-info@2.4.2 
  │ │   │   ├─┬ is-builtin-module@1.0.0 
  │ │   │   │ └── builtin-modules@1.1.1 
  │ │   │   ├── semver@5.3.0 
  │ │   │   └─┬ validate-npm-package-license@3.0.1 
  │ │   │     ├─┬ spdx-correct@1.0.2 
  │ │   │     │ └── spdx-license-ids@1.2.2 
  │ │   │     └── spdx-expression-parse@1.0.4 
  │ │   └── readdir-scoped-modules@1.0.2 
  │ └─┬ yargs@7.1.0 
  │   ├── camelcase@3.0.0 
  │   ├─┬ cliui@3.2.0 
  │   │ ├─┬ strip-ansi@3.0.1 
  │   │ │ └── ansi-regex@2.1.1 
  │   │ └── wrap-ansi@2.1.0 
  │   ├── decamelize@1.2.0 
  │   ├── get-caller-file@1.0.2 
  │   ├─┬ os-locale@1.4.0 
  │   │ └─┬ lcid@1.0.0 
  │   │   └── invert-kv@1.0.0 
  │   ├─┬ read-pkg-up@1.0.1 
  │   │ ├─┬ find-up@1.1.2 
  │   │ │ └── path-exists@2.1.0 
  │   │ └─┬ read-pkg@1.1.0 
  │   │   ├─┬ load-json-file@1.1.0 
  │   │   │ ├─┬ parse-json@2.2.0 
  │   │   │ │ └─┬ error-ex@1.3.1 
  │   │   │ │   └── is-arrayish@0.2.1 
  │   │   │ ├── pify@2.3.0 
  │   │   │ └─┬ strip-bom@2.0.0 
  │   │   │   └── is-utf8@0.2.1 
  │   │   └── path-type@1.1.0 
  │   ├── require-directory@2.1.1 
  │   ├── require-main-filename@1.0.1 
  │   ├── set-blocking@2.0.0 
  │   ├─┬ string-width@1.0.2 
  │   │ ├── code-point-at@1.1.0 
  │   │ └─┬ is-fullwidth-code-point@1.0.0 
  │   │   └── number-is-nan@1.0.1 
  │   ├── which-module@1.0.0 
  │   ├── y18n@3.2.1 
  │   └── yargs-parser@5.0.0 
  └─┬ pown-dist@0.8.0 
    ├─┬ pown-captcha@0.3.0 
    │ ├─┬ chalk@1.1.3 
    │ │ ├── ansi-styles@2.2.1 
    │ │ ├── escape-string-regexp@1.0.5 
    │ │ ├── has-ansi@2.0.0 
    │ │ └── supports-color@2.0.0 
    │ └─┬ tesseract.js@1.0.10 
    │   ├── file-type@3.9.0 
    │   ├── is-url@1.2.2 
    │   ├── jpeg-js@0.2.0 
    │   ├─┬ level-js@2.2.4 
    │   │ ├─┬ abstract-leveldown@0.12.4 
    │   │ │ └── xtend@3.0.0 
    │   │ ├── idb-wrapper@1.7.1 
    │   │ ├── isbuffer@0.0.0 
    │   │ ├── ltgt@2.1.3 
    │   │ ├── typedarray-to-buffer@1.0.4 
    │   │ └─┬ xtend@2.1.2 
    │   │   └── object-keys@0.4.0 
    │   ├─┬ node-fetch@1.6.3 
    │   │ ├─┬ encoding@0.1.12 
    │   │ │ └── iconv-lite@0.4.16 
    │   │ └── is-stream@1.1.0 
    │   ├── object-assign@4.1.1 
    │   ├── png.js@0.2.1 
    │   └── tesseract.js-core@1.0.2 
    ├─┬ pown-credits@0.2.0 
    │ └── pown-modules@0.4.3 
    ├─┬ pown-now@0.1.0 
    │ ├─┬ opn@4.0.2 
    │ │ └─┬ pinkie-promise@2.0.1 
    │ │   └── pinkie@2.0.4 
    │ ├─┬ ws@2.3.1 
    │ │ ├── safe-buffer@5.0.1 
    │ │ └── ultron@1.1.0 
    │ └─┬ ws-pcap2@3.3.1 
    │   ├── nan@2.6.2 
    │   └── socketwatcher@0.3.0 
    ├─┬ pown-responder@0.1.4 
    │ ├─┬ dns-js@0.2.1 
    │ │ ├─┬ debug@2.6.4 
    │ │ │ └── ms@0.7.3 
    │ │ └── qap@3.1.3 
    │ └─┬ ip-address@5.8.8 
    │   ├── jsbn@0.1.0 
    │   ├── lodash.find@4.6.0 
    │   ├── lodash.max@4.0.1 
    │   ├── lodash.merge@4.6.0 
    │   ├── lodash.padstart@4.6.1 
    │   ├── lodash.repeat@4.1.0 
    │   ├── sprintf-js@1.0.3 
    │   └── util-deprecate@1.0.2 
    └─┬ pown-tips@0.0.2 
      ├─┬ inquirer@3.0.6 
      │ ├── ansi-escapes@1.4.0 
      │ ├─┬ cli-cursor@2.1.0 
      │ │ └─┬ restore-cursor@2.0.0 
      │ │   ├─┬ onetime@2.0.1 
      │ │   │ └── mimic-fn@1.1.0 
      │ │   └── signal-exit@3.0.2 
      │ ├── cli-width@2.1.0 
      │ ├─┬ external-editor@2.0.1 
      │ │ └─┬ tmp@0.0.31 
      │ │   └── os-tmpdir@1.0.2 
      │ ├── figures@2.0.0 
      │ ├── mute-stream@0.0.7 
      │ ├─┬ run-async@2.3.0 
      │ │ └── is-promise@2.1.0 
      │ ├── rx@4.1.0 
      │ ├─┬ string-width@2.0.0 
      │ │ └── is-fullwidth-code-point@2.0.0 
      │ └── through@2.3.8 
      ├── marked@0.3.6 
      ├─┬ marked-terminal@2.0.0 
      │ ├─┬ cardinal@1.0.0 
      │ │ ├── ansicolors@0.2.1 
      │ │ └─┬ redeyed@1.0.1 
      │ │   └── esprima@3.0.0 
      │ ├─┬ cli-table@0.3.1 
      │ │ └── colors@1.0.3 
      │ ├── lodash.assign@4.2.0 
      │ └─┬ node-emoji@1.5.1 
      │   └── string.prototype.codepointat@0.2.0 
      └── wordwrap@1.0.0 

```

**Comment by illnino** [comment]
It looks like after uninstalling & re-installing the package, it is working now.

**Comment by pdparchitect** [comment]
Glad it worked! I will keep an eye on similar reports.
