### ISSUE TITLE
Failed install

### ISSUE THREAD

**Issue by lowolf** [pownjs/pown-now#2]
```
npm install pown-now --save

> socketwatcher@0.3.0 install /usr/local/Cellar/libimobiledevice/HEAD-26373b3_2/node_modules/socketwatcher
> node-gyp rebuild

  CXX(target) Release/obj.target/socketwatcher/socket_watcher.o
../socket_watcher.cpp:77:8: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
  Nan::MakeCallback(watcher->handle(), callback, argc, argv);
       ^
../../nan/nan.h:929:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../socket_watcher.cpp:104:37: error: no matching member function for call to 'NewInstance'
    info.GetReturnValue().Set(cons->NewInstance());
                              ~~~~~~^~~~~~~~~~~
/Users/.node-gyp/10.8.0/include/node/v8.h:3956:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
/Users/.node-gyp/10.8.0/include/node/v8.h:3953:44: note: candidate function not viable: requires 3 arguments, but 0 were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
1 warning and 1 error generated.
make: *** [Release/obj.target/socketwatcher/socket_watcher.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/lib/node_modules/node/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/Cellar/libimobiledevice/HEAD-26373b3_2/node_modules/socketwatcher
gyp ERR! node -v v10.8.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/usr/local/Cellar/libimobiledevice/HEAD-26373b3_2/package.json'
npm WARN HEAD-26373b3_2 No description
npm WARN HEAD-26373b3_2 No repository field.
npm WARN HEAD-26373b3_2 No README data
npm WARN HEAD-26373b3_2 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! socketwatcher@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the socketwatcher@0.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by yannbertrand** [comment]
I also have this error using node v10. Try with node v6

**Comment by pdparchitect** [comment]
Project archived until we move to version x2 which will resolve all of these issues.
